# Note: This is an example configuration file, change to config.yaml to run script
# You do not need to provide a username and secret here if you would like to use the same username and secret for all devices
# You also do not need to provide domainname if you would like it to be the same for all devices
# Find supported device types here (This script only supports cisco juniper and cumulus)https://ktbyers.github.io/netmiko/PLATFORMS.html

Globals:
  username: user
  domainname: domain.local
  default_gateway: 192.168.1.1
  mgt_mask: 255.255.255.192
  tftp_server: 192.168.1.2


# This script supports cisco L2 Switch at the moment, will support more devices in the future
# Change the Dev_Name when you add new devices if you want to have good documentation
Dev_Name:
  device_type: cisco
  # GNS3 Host IP (Or whatever telnet host you're using)
  host: 192.168.1.2
  # Telnet port
  port: 5000
  Layer: "L2Switch"
  hostname: hostname
  # Don't need to change this if you want the same domain name for all devices, just change the globals
  domain_name: domain.tld
  # Management IP (IP to give the device for the mgt network)
  mgt_ip: 192.168.1.3
  mgt_mask: 255.255.255.0